config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'incoming_emails#index'
  resources :incoming_emails, only: %i[new create index show]
  resources :customers, only: %i[index show]
  resources :email_processings, only: %i[index show]
end

app/models/application_record.rb
# app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
# app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  validate :contact_present
  belongs_to :incoming_email

  def contact_present
    return unless email.blank? && phone.blank?

    errors.add(:base, 'Need email and phone')
  end
end

app/models/email_processing.rb
# app/models/email_processing.rb
class EmailProcessing < ApplicationRecord
  belongs_to :incoming_email
end

app/models/incoming_email.rb
# app/models/incoming_email.rb
class IncomingEmail < ApplicationRecord
  has_many :email_processings, dependent: :destroy
  has_one :customer
  has_one_attached :file

  validates :file, presence: true

  before_validation :set_filename

  private

  def set_filename
    return unless file.attached?

    self.filename = file.filename.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/incoming_emails_controller.rb
# Controller for managing incoming emails
class IncomingEmailsController < ApplicationController
  rescue_from ActionController::ParameterMissing, with: :missing_file

  def index
    @incoming_emails = IncomingEmail.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @incoming_email = IncomingEmail.find(params[:id])
  end

  def new
    @incoming_email = IncomingEmail.new
  end

  def create
    @incoming_email = IncomingEmail.new(incoming_email_params)

    if @incoming_email.save
      ProcessIncomingEmailWorker.perform_async(@incoming_email.id)
      redirect_to incoming_emails_path, notice: t('.file_sent')
    else
      render :new
    end
  end

  private

  def incoming_email_params
    params.require(:incoming_email).permit(:file)
  end

  def missing_file
    flash[:alert] = t('.file_required')
    redirect_back_or_to(incoming_emails_path)
  end
end

app/helpers/application_helper.rb
# helper used in code.
module ApplicationHelper
  # Counts incoming emails based on their status.
  def count_incoming_emails(status)
    {
      'all' => IncomingEmail.count,
      'pending' => IncomingEmail.where(status: 'pending').count,
      'processing' => IncomingEmail.where(status: 'processing').count,
      'failed' => IncomingEmail.where(status: 'failed').count,
      'success' => IncomingEmail.where(status: 'success').count
    }.fetch(status, 0)
  end

  # Returns the color badge for a given status.
  def color_badge(status)
    {
      'pending' => 'black',
      'processing' => 'warning',
      'failed' => 'danger',
      'success' => 'success'
    }.fetch(status, 'secondary')
  end

  # Returns the color alert for a given status.
  def bootstrap_class_for(type)
    type = type.to_s

    return 'success' if %w[success notice].include?(type)
    return 'danger'  if %w[error alert danger].include?(type)
    return 'warning' if type == 'warning'
    return 'info'    if type == 'info'

    'secondary'
  end
end

app/helpers/incoming_emails_helper.rb
# Helper methods for IncomingEmails
module IncomingEmailsHelper
end

app/views/incoming_emails/index.html.erb
<div class="row mx-auto d-flex justify-content-center">

    <div class="col-md-2 mb-3">
        <div class="card bg-primary text-light">
            <div class="card-header">
                Total
            </div>
            <div class="card-body text-center">
                <%= count_incoming_emails("all")%>
            </div>
        </div>
    </div>

    <div class="col-md-2 mb-3">
        <div class="card bg-dark text-light">
            <div class="card-header">
                Pending
            </div>
            <div class="card-body text-center">
                <%= count_incoming_emails("pending") %>
            </div>
        </div>
    </div>

    <div class="col-md-2 mb-3">
        <div class="card bg-warning text-light">
            <div class="card-header">
                Processing
            </div>
            <div class="card-body text-center">
                <%= count_incoming_emails("processing")%>
            </div>
        </div>
    </div>

    <div class="col-md-2 mb-3">
        <div class="card bg-danger text-light">
            <div class="card-header">
                Failed
            </div>
            <div class="card-body text-center">
                <%= count_incoming_emails("failed") %>
            </div>
        </div>
    </div>

    <div class="col-md-2 mb-3">
        <div class="card bg-success text-light">
            <div class="card-header">
                Success
            </div>
            <div class="card-body text-center">
                <%= count_incoming_emails("success") %>
            </div>
        </div>
    </div>

</div>
<div class="my-4">
    <h3>Incoming Emails</h3>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <th>#</th>
        <th>filename</th>
        <th>status</th>
        <th>created at</th>
        <th>Options</th>
    </thead>
    <tbody>
        <% @incoming_emails.each do |incoming_email| %>
            <tr>
                <td><%= incoming_email.id %></td>
                <td><%= incoming_email.filename %></td>
                <td>
                    <span class="badge bg-<%= color_badge(incoming_email.status) %>"><%= incoming_email.status %></span>
                </td>
                <td><%= incoming_email.created_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
                <td><%= link_to "details", incoming_email_path(incoming_email.id)%></td>
            </tr>
        <% end %>
    </tbody>
</table>
<div class="d-flex justify-content-center">
    <%= paginate @incoming_emails %>
</div>
<div class="d-flex justify-content-end">
    <%= link_to "New", new_incoming_email_path, class: "btn btn-sm btn-success" %>
</div>

app/views/incoming_emails/new.html.erb
<div class="card">
  <div class="card-header">
    Send Archive .eml Form
  </div>

  <div class="card-body">
    <%= form_with model: @incoming_email, local: true, html: { multipart: true } do |form| %>

      <div class="mb-3">
        <%= form.label :file, ".eml File", class: "form-label" %>
        <%= form.file_field :file, accept: ".eml", class: "form-control" %>
      </div>

      <div class="d-flex justify-content-end">
        <%= link_to "Back", incoming_emails_path, class: "btn btn-secondary mx-2" %>
        <%= form.submit "Send", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/incoming_emails/show.html.erb
<div class="card">
    <div class="card-header">
        Incoming email details nº: <%= @incoming_email.id %>
    </div>
    <div class="card-body">
        <div class="d-flex justify-content-end mb-3">
            <span class="badge bg-<%= color_badge(@incoming_email.status) %>"><%= @incoming_email.status %></span>
        </div>
        <div class="mb-3">
            <%= label_tag :filename, "Filename", class: "form-label" %>
            <%= text_field_tag :filename, @incoming_email.filename, readonly: true, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= label_tag :sender, "Sender", class: "form-label" %>
            <%= text_field_tag :filename, @incoming_email.sender, readonly: true, class: "form-control" %>
        </div>
        <% unless @incoming_email.customer.nil? %>
            <div class="card mb-3">
                <div class="card-header">
                    Customer details
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <%= label_tag :name, "Subject", class: "form-label" %>
                        <%= text_field_tag :name, @incoming_email.customer.subject, readonly: true, class: "form-control" %>
                    </div>
                    <div class="mb-3">
                        <%= label_tag :name, "Name", class: "form-label" %>
                        <%= text_field_tag :name, @incoming_email.customer.name, readonly: true, class: "form-control" %>
                    </div>
                    <div class="mb-3">
                        <%= label_tag :email, "Email", class: "form-label" %>
                        <%= text_field_tag :email, @incoming_email.customer.email, readonly: true, class: "form-control" %>
                    </div>
                    <div class="mb-3">
                        <%= label_tag :phone, "Phone", class: "form-label" %>
                        <%= text_field_tag :phone, @incoming_email.customer.phone, readonly: true, class: "form-control" %>
                    </div>
                    <div class="mb-3">
                        <%= label_tag :name, "Product Code", class: "form-label" %>
                        <%= text_field_tag :name, @incoming_email.customer.product_code, readonly: true, class: "form-control" %>
                    </div>
                </div>
            </div>
        <% end %>
        <div class="card mb-3">
            <div class="card-header">
                Email processings details
            </div>
            <div class="card-body">
                <% if @incoming_email.email_processings.size > 0 %>
                    <% @incoming_email.email_processings.each do |email_processing| %>
                        <div class="card p-3">
                            <div class="mb-3">
                                Success? <%= email_processing.success %>
                            </div>
                            <% unless email_processing.success? %>
                                <div class="mb-3">
                                    <%= label_tag "Error message" %>
                                    <%= text_area_tag :error_message, email_processing.error_message, cols: 80, rows: 10, class: "form-control", disabled: true %>
                                </div>
                            <% end %>
                            <div class="mb-3">
                                <%= label_tag "Extracted data" %>
                                <%= text_area_tag :error_message, email_processing.extracted_data, cols: 80, rows: 10, class: "form-control", disabled: true %>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    No informations at moment
                <% end %>
            </div>
        </div>
        <div class="d-flex justify-content-end">
            <%= link_to "Back", incoming_emails_path, class: "btn btn-secondary" %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParserEml</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <% flash.each do |key, message| %>
      <div class="alert alert-<%= bootstrap_class_for(key) %> shadow mx-5 col-12 alert-dismissible fade show" style="position: fixed; top: 20px; right: 0; z-index: 9999; width: auto; max-width: 90%;" role="alert">
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="mt-5">
      <%= yield %>
    </div>
    <%= javascript_importmap_tags %>
  </body>
</html>